### ISSUE TITLE
Expected newline after "," (selector-list-comma-newline-after)

### ISSUE THREAD

**Issue by leanny01** [BuildForSDGCohort2/Team-258-group-a-frontend#68]
#### Currently on:
+ **Commit**:  75adbf7399069d95e9e6e6160354394b0204b935
+ **File**:    [css/html5reset.css](https://github.com/BuildForSDGCohort2/Team-258-group-a-frontend/blob/75adbf7399069d95e9e6e6160354394b0204b935/css/html5reset.css)
+ **LineNum**: [4](https://github.com/BuildForSDGCohort2/Team-258-group-a-frontend/blob/75adbf7399069d95e9e6e6160354394b0204b935/css/html5reset.css#L4)

**Comment by Eunit99** [comment]
Fixed
