### ISSUE TITLE
Expected no more than 1 empty line (max-empty-lines)

### ISSUE THREAD

**Issue by leanny01** [BuildForSDGCohort2/Team-258-group-a-frontend#73]
#### Occurred on:
+ **Commit**:  f5aceedf64d40a0c4942ca896efdbf28fde0502f
+ **File**:    [css/styles.css](https://github.com/BuildForSDGCohort2/Team-258-group-a-frontend/blob/f5aceedf64d40a0c4942ca896efdbf28fde0502f/css/styles.css)
+ **LineNum**: [49](https://github.com/BuildForSDGCohort2/Team-258-group-a-frontend/blob/f5aceedf64d40a0c4942ca896efdbf28fde0502f/css/styles.css#L49)
+ **Code**:    ``

    
#### Currently on:
+ **Commit**:  75adbf7399069d95e9e6e6160354394b0204b935
+ **File**:    [css/styles.css](https://github.com/BuildForSDGCohort2/Team-258-group-a-frontend/blob/75adbf7399069d95e9e6e6160354394b0204b935/css/styles.css)
+ **LineNum**: [49](https://github.com/BuildForSDGCohort2/Team-258-group-a-frontend/blob/75adbf7399069d95e9e6e6160354394b0204b935/css/styles.css#L49)

**Comment by Eunit99** [comment]
Fixed
