### ISSUE TITLE
Unexpected whitespace before ";" (declaration-block-semicolon-space-before)

### ISSUE THREAD

**Issue by leanny01** [BuildForSDGCohort2/Team-258-group-a-frontend#76]
#### Occurred on:
+ **Commit**:  12f1691080c6f2c0f51f26e5877c5d9952520fb3
+ **File**:    [css/theme.css](https://github.com/BuildForSDGCohort2/Team-258-group-a-frontend/blob/12f1691080c6f2c0f51f26e5877c5d9952520fb3/css/theme.css)
+ **LineNum**: [18](https://github.com/BuildForSDGCohort2/Team-258-group-a-frontend/blob/12f1691080c6f2c0f51f26e5877c5d9952520fb3/css/theme.css#L18)
+ **Code**:    `--font_family: ;`

    
#### Currently on:
+ **Commit**:  75adbf7399069d95e9e6e6160354394b0204b935
+ **File**:    [css/theme.css](https://github.com/BuildForSDGCohort2/Team-258-group-a-frontend/blob/75adbf7399069d95e9e6e6160354394b0204b935/css/theme.css)
+ **LineNum**: [18](https://github.com/BuildForSDGCohort2/Team-258-group-a-frontend/blob/75adbf7399069d95e9e6e6160354394b0204b935/css/theme.css#L18)

**Comment by Eunit99** [comment]
Fixed
